version: "3.9"
services:
  web:
    build:
      context: ./nginx
    ports:
     - "8080:80"
    environment:
     - NGINX_PORT=80
  app:
    build:
      context: ./app
    ports:
      - "8000:8000"